### ISSUE TITLE
Is this license approved by a lawyer?

### ISSUE THREAD

**Issue by janTatesa** [JoakimCh/Simple-Copyleft-License-v1#1]
can you please tell me, is it safe to use this license? Did you consult a lawyer about this license?

**Comment by JoakimCh** [comment]
I don't have enough money to consult a lawyer.

Anyone is free to write custom licenses and bind it with whatever they publish. People must by law then follow that license! But a badly worded license could cause confusion and such confusion could lead to a lawsuit; to let it be decided there if it was actually misused.

So if anyone misuse (doesn't follow it) whatever license you decide on using then you could sue them and would most likely win.

Is it a good idea to use my license? I don't know, to me it feels like a very good license. But I have not managed to get feedback on it, because I have no friends or followers that I have told about it. Other than me, maybe you're the only one who have read about it...

Maybe there is a Reddit forum where you can ask this question and get a better answer. Myself I have decided to use a MIT license for most of my stuff, since people are familiar with it. But I might use this instead on my next big project, because it's the only license I've seen which forces proper credit to original authors.

**Comment by janTatesa** [comment]
Thanks for your answer. I will post a reddit post about it. By the way 4clause bsd is not copyleft but enforces credit to author so its a good alternative to mit

**Comment by JoakimCh** [comment]
I found the related discussion:
https://www.reddit.com/r/opensource/comments/173leqm/is_this_license_okay_to_use/
Their feedback is sad to hear, but I appreciate their honesty.
